### ISSUE TITLE
intermittent failing spec

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-codec-multiline#46]
```
1) LogStash::Codecs::IdentityMapCodec observer/listener based processing normal processing when wrapped codec has auto-flush activated three events are auto flushed from three different identities/codecs
     Failure/Error: expect(queue.size).to eq(3)

       expected: 3
            got: 0

       (compared using ==)
     # ./spec/codecs/identity_map_codec_spec.rb:238:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'

Finished in 31.87 seconds (files took 4.7 seconds to load)
42 examples, 1 failure

Failed examples:

rspec ./spec/codecs/identity_map_codec_spec.rb:236 # LogStash::Codecs::IdentityMapCodec observer/listener based processing normal processing when wrapped codec has auto-flush activated three events are auto flushed from three different identities/codecs

Randomized with seed 3175
```

**Comment by PadaKwaak** [comment]
@jsvd : I also consistently get that very same error when running `bundle exec rspec --seed 3175`.

I've also stumbled upon another failure when using `bundle exec rspec --seed 58183` (from my topic: #48):

```
Failures:

  1) LogStash::Codecs::Multiline auto flushing when the auto_flush raises an exception does not build any events, logs an error and the buffer data remains
     Failure/Error: expect(msg).to eq("Multiline: flush downstream error")

       expected: "Multiline: flush downstream error"
            got: false

       (compared using ==)
     # ./spec/codecs/multiline_spec.rb:267:in `block in (root)'
     # /usr/local/rvm/gems/jruby-9.0.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'

Finished in 33.6 seconds (files took 8.03 seconds to load)
42 examples, 1 failure

Failed examples:

rspec ./spec/codecs/multiline_spec.rb:261 # LogStash::Codecs::Multiline auto flushing when the auto_flush raises an exception does not build any events, logs an error and the buffer data remains

Randomized with seed 58183
```
